/* A parser generated by PackCC 3.1.0 */

#ifndef PCC_INCLUDED_AXOLANG_H
#define PCC_INCLUDED_AXOLANG_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct axolang_context_tag axolang_context_t;

axolang_context_t *axolang_create(void *auxil);
int axolang_parse(axolang_context_t *ctx, char **ret);
void axolang_destroy(axolang_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_AXOLANG_H */
